#!/usr/bin/env python3
"""Build the English and Chinese CVs.

Publications are read from ../_data/publications.yml (the same file the website
uses), turned into LaTeX lists in generated/pubs.tex, and both CVs are compiled
with XeLaTeX. The PDFs are copied to ../files/.

    cd _cv_src && python3 build.py
"""
import re
import shutil
import subprocess
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
DATA = yaml.safe_load((ROOT / "_data" / "publications.yml").read_text(encoding="utf-8"))

STAR = "\uE000"  # placeholder for the corresponding-author mark


def md_to_tex(text: str) -> str:
    t = text.replace("\\*", STAR)
    for a, b in [("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("#", r"\#"),
                 ("_", r"\_"), ("$", r"\$"), ("~", r"\textasciitilde{}")]:
        t = t.replace(a, b)
    t = re.sub(r"\*\*(.+?)\*\*", r"\\textbf{\1}", t)
    t = re.sub(r"\*(.+?)\*", r"\\emph{\1}", t)
    return t.replace(STAR, r"\corr{}")


def link_label(url: str) -> str:
    if "doi.org/" in url:
        return "doi:" + url.split("doi.org/", 1)[1]
    if "arxiv.org" in url:
        return "arXiv:" + url.rstrip("/").split("/")[-1]
    return "link"


def items(group: str, prefix: str, start: int) -> str:
    out = []
    n = start
    for p in DATA.get(group, []):
        line = md_to_tex(p["text"].strip())
        if p.get("link"):
            line += r"\pubdoi{%s}{%s}" % (p["link"], link_label(p["link"]))
        out.append(r"\item[%s%d] %s" % (prefix, n, line))
        n -= 1
    return "\n".join(out)


n_cn = len(DATA.get("chinese", []))
n_j = len(DATA.get("journal", []))
gs = DATA.get("scholar", {})

gen = HERE / "generated"
gen.mkdir(exist_ok=True)
(gen / "pubs.tex").write_text("\n".join([
    "% generated by build.py from _data/publications.yml -- do not edit",
    r"\newcommand{\GSCitations}{%s}" % gs.get("citations", ""),
    r"\newcommand{\GSh}{%s}" % gs.get("h_index", ""),
    r"\newcommand{\GSiten}{%s}" % gs.get("i10_index", ""),
    r"\newcommand{\GSupdated}{%s}" % gs.get("updated", ""),
    r"\newcommand{\GSurl}{%s}" % gs.get("url", ""),
    r"\newcommand{\NJournal}{%d}" % (n_j + n_cn),
    r"\newcommand{\PubsJournal}{%s}" % items("journal", "J", n_j + n_cn),
    r"\newcommand{\PubsChinese}{%s}" % items("chinese", "J", n_cn),
    r"\newcommand{\PubsReview}{%s}" % items("under_review", "R", len(DATA.get("under_review", []))),
    r"\newcommand{\PubsConference}{%s}" % items("conference", "C", len(DATA.get("conference", []))),
    r"\newcommand{\PubsThesis}{%s}" % items("thesis", "T", len(DATA.get("thesis", []))),
    ""]), encoding="utf-8")

out_dir = ROOT / "files"
out_dir.mkdir(exist_ok=True)
# The Chinese CV is built inside _cv_src only (not published on the website).
for src, dst in [("cv-en.tex", "Jidu_Yu_CV.pdf"), ("cv-zh.tex", None)]:
    for _ in range(2):  # second pass resolves "page x of y"
        subprocess.run(["xelatex", "-interaction=nonstopmode", "-halt-on-error", src],
                       cwd=HERE, check=True, stdout=subprocess.DEVNULL)
    if dst:
        shutil.copy(HERE / src.replace(".tex", ".pdf"), out_dir / dst)
        print("wrote", out_dir / dst)


# ---- Overleaf packages: one self-contained zip per CV (XeLaTeX via latexmkrc) ----
import zipfile
for lang, tex in [("en", "cv-en.tex"), ("zh", "cv-zh.tex")]:
    zpath = (out_dir if lang == "en" else HERE) / f"Jidu_Yu_CV_{lang}_latex.zip"
    with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as z:
        z.write(HERE / tex, "main.tex")
        z.write(HERE / "cvstyle.sty", "cvstyle.sty")
        z.write(gen / "pubs.tex", "generated/pubs.tex")
        z.writestr("latexmkrc", "$pdf_mode = 5;  # XeLaTeX\n")
        if lang == "zh":
            z.write(HERE / "photo.jpg", "photo.jpg")
        for f in sorted((HERE / "fonts").iterdir()):
            z.write(f, f"fonts/{f.name}")
    print("wrote", zpath)
